info:
  version: "@project.version@"
  title: Encrypt api

server:
  port: 8084

encryption:
  secret-key: "TXLrNhQOgmrkAs8m"  # Clave de 16 caracteres
  algorithm: "AES/ECB/PKCS5Padding"
  base-algorithm: "AES"


spring:
  profiles.active: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://host.docker.internal:8181/realms/demo-realm/protocol/openid-connect/certs
  webflux:
    base-path: /api/v1

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: /swagger.yaml

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    org.springframework: DEBUG
    com.financial: DEBUG
  date-format: yyyy-MM-dd HH:mm:ss

